name: frontend-cd
on:
  workflow_dispatch:
  push:
    branches: 
      - main
    paths: 
      - starter/frontend

env:
  ECR_REPO_NAME: 334677819384.dkr.ecr.us-east-1.amazonaws.com/cherkavi-udacity-github-action-fe
  CONTAINER_TAG: '1.0.1'
  API_URL: 'backend_service'

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3 
    - name: lint
      run: npm --prefix starter/frontend install && npm --prefix starter/frontend run lint

  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3 
    - name: lint
      run: npm --prefix starter/frontend install && CI=true npm --prefix starter/frontend test

  build:
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
    - name: Checkout
      uses: actions/checkout@v3 
    - name: build
      run: npm --prefix starter/frontend install && CI=true npm --prefix starter/frontend run build

    - name: Set environment variable
      run: echo "DEST_VERSION=${{ env.NODE_VERSION }}" >> $GITHUB_ENV
    - name: 'build docker image'
      uses: 'docker/build-push-action@v2'
      with:
        context: starter/frontend
        file: starter/frontend/Dockerfile
        build-args: "REACT_APP_MOVIE_API_URL=${{ env.API_URL }}"
        tags: ${{ env.ECR_REPO_NAME }}:${{ env.CONTAINER_TAG }}
